backend:
  name: git-gateway
media_folder: /source/media/uploads
public_folder: /media/uploads
collections:
  - name: socials
    label: Social Networks
    folder: /data/socials
    format: yml
    fields:
      - { label: Network, name: title, widget: string }
      - { label: URL, name: url, widget: string }
      - { label: Font Awesome Code, name: facode, widget: string, comment: This is the Font Awesome code for the icon, can be found at https://fontawesome.com/icons?d=gallery }
  - name: classes
    label: Class Timetable
    folder: /data/classes
    format: yml
    fields:
      - { label: Name, name: title, widget: string }
      - { label: Day, name: day, widget: select, options: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday] }
      - { label: Start Time, name: start_time, widget: string }
      - { label: End Time, name: end_time, widget: string }
      - { label: Level, name: level, widget: select, options: [Beginner, Intermediate, Advanced] }
      - { label: Location, name: location, widget: string }
      - { label: Cost, name: cost, widget: string }
  - name: dances
    label: Dance List
    folder: /data/dances
    format: yml
    fields:
      - { label: Name, name: title, widget: string }
      - { label: External URL, name: url, widget: string }
      - { label: Choreographer, name: choreographer, widget: string }
      - { label: Song & Artist, name: song_artist, widget: string }
      - { label: Level, name: level, widget: select, options: [Beginner, Intermediate, Advanced] }
      - { label: Date, name: date, widget: string }
  - name: general
    label: General Settings
    folder: /data/settings
    files:
      - file: about.yml
        name: about
        label: About MM Line Dancing
        fields: 
          - { label: About Blurb, name: blurb, widget: text, comment: TLDR; Use <p> at the end of each paragraph!\nYou will need to use proper html codes for the text to format correctly. Mostly that just means putting <p> at the end of each paragraph the break up text nicely. }