---
new_page_extension: html
auto_deploy: false
admin_path: source/admin/cms
webhook_url: 
sections:
- type: directory
  path: data/classes
  label: Class Timetable
  create: documents
  match: "**/*"
  new_doc_ext: yml
- type: directory
  path: data/dances
  label: Dance List
  create: documents
  match: "**/*"
  new_doc_ext: yml
- type: directory
  path: data/socials
  label: Social Network Links
  create: documents
  match: "**/*"
  new_doc_ext: yml
- type: heading
  label: Settings
- type: document
  path: data/settings/about.yml
  label: About MM Line Dancing
upload_dir: source/images
public_path: "/images"
front_matter_path: "/data"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: build
  install_dependencies_command: bundle install --path vendor/bundle && npm install
  preview_docker_image: forestryio/ruby:2.6-node12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: NO_CONTRACTS=true bundle exec middleman build --clean
