---
new_page_extension: html
auto_deploy: false
admin_path: source/cms
webhook_url: 
sections:
- type: directory
  path: source
  label: Pages
  create: none
  match: "*.html.erb"
  templates:
  - page
- type: heading
  label: Site Content
- type: directory
  path: data/classes
  label: Class Timetable
  create: documents
  match: "**/*"
  new_doc_ext: yml
- type: directory
  path: data/dances
  label: Dance List
  create: documents
  match: "**/*"
  new_doc_ext: yml
- type: directory
  path: data/socials
  label: Social Network Links
  create: documents
  match: "**/*"
  new_doc_ext: yml
- type: document
  path: data/settings/about.yml
  label: About MM Line Dancing
- type: heading
  label: Site Settings (In Progress)
- type: document
  path: data/settings/class-levels.yml
  label: Class Levels
- type: document
  path: data/settings/navigation.yml
  label: Navigation Links
upload_dir: source/images
public_path: "/images"
front_matter_path: "/data"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: build
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6-node12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: NO_CONTRACTS=true bundle exec middleman build --clean
