---
new_page_extension: html
auto_deploy: false
admin_path: source/admin/cms
webhook_url: 
sections: 
upload_dir: source/uploads
public_path: "/uploads"
front_matter_path: "/data"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: build
  install_dependencies_command: bundle install
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec middleman build
